In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# Define o número máximo de colunas e a largura máxima das colunas para None
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [43]:
df = pd.read_csv(r"C:\Users\gusta\OneDrive\Área de Trabalho\Facens\TCC\DataSets\INFLUD23-26-02-2024.csv", delimiter=';')

C:\Users\gusta\AppData\Local\Temp\ipykernel_17020\4056821837.py:1: DtypeWarning: Columns (15,18,20,23,53,59,61,63,72,74,79,91,93,109,130,175,178) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\gusta\OneDrive\Área de Trabalho\Facens\TCC\DataSets\INFLUD23-26-02-2024.csv", delimiter=';')

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277304 entries, 0 to 277303
Columns: 190 entries, DT_NOTIFIC to TABAG
dtypes: float64(99), int64(7), object(84)
memory usage: 402.0+ MB

In [45]:
df.head()

,DT_NOTIFIC,SEM_NOT,DT_SIN_PRI,SEM_PRI,SG_UF_NOT,ID_REGIONA,CO_REGIONA,ID_MUNICIP,CO_MUN_NOT,ID_UNIDADE,...,VG_ENC,VG_REINF,REINF,FAB_ADIC,LOT_RE_BI,FAB_RE_BI,DOSE_ADIC,DOS_RE_BI,LOTE_ADIC,TABAG
0,08/02/2023,6,23/01/2023,4,RS,014 CRS,1602.0,CAMPINA DAS MISSOES,430370,POSTO DE SAUDE SEDE E PACS CAMPINA DAS MISSOES,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,27/02/2023,9,25/02/2023,8,PR,02RS METROPOLITANA,1356.0,CURITIBA,410690,HOSPITAL UNIVERSITARIO EVANGELICO MACKENZIE,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17/03/2023,11,12/03/2023,11,SP,GVE XVI BOTUCATU,1341.0,BOTUCATU,350750,HOSPITAL UNIMED BOTUCATU,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21/03/2023,12,18/03/2023,11,PR,17RS LONDRINA,1371.0,LONDRINA,411370,HOSPITAL DO CORACAO UNIDADE BELA SUICA,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,29/03/2023,13,26/03/2023,13,SC,SAO MIGUEL DO OESTE,1548.0,GUARACIABA,420640,ASSOCIACAO BENEFICIENTE HOSPITAL SAO LUCAS,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
df.columns

Index(['DT_NOTIFIC', 'SEM_NOT', 'DT_SIN_PRI', 'SEM_PRI', 'SG_UF_NOT',
       'ID_REGIONA', 'CO_REGIONA', 'ID_MUNICIP', 'CO_MUN_NOT', 'ID_UNIDADE',
       ...
       'VG_ENC', 'VG_REINF', 'REINF', 'FAB_ADIC', 'LOT_RE_BI', 'FAB_RE_BI',
       'DOSE_ADIC', 'DOS_RE_BI', 'LOTE_ADIC', 'TABAG'],
      dtype='object', length=190)

# Cleaning

In [47]:
# Supondo que 'df' seja o seu DataFrame original
# Substitua 'df' pelo nome do seu DataFrame

# Calcula a porcentagem de valores nulos em cada coluna
null_percentage = df.isnull().mean() * 100

# Seleciona as colunas com mais de 75% de valores nulos
columns_with_high_null_percentage = null_percentage[null_percentage > 80]
print(columns_with_high_null_percentage)

# Cria um novo DataFrame com as colunas selecionadas e suas porcentagens de valores nulos
new_df = pd.DataFrame(columns_with_high_null_percentage, columns=['Porcentagem de Nulos'])

new_df.head()

OBES_IMC       99.766321
MORB_DESC      81.270014
DT_UT_DOSE     96.427026
MAE_VAC        93.987104
DT_VAC_MAE     99.789401
                 ...
FAB_RE_BI      92.585394
DOSE_ADIC      98.195843
DOS_RE_BI      92.580345
LOTE_ADIC      98.218201
TABAG         100.000000
Length: 84, dtype: float64

            Porcentagem de Nulos
OBES_IMC               99.766321
MORB_DESC              81.270014
DT_UT_DOSE             96.427026
MAE_VAC                93.987104
DT_VAC_MAE             99.789401

In [48]:
new_df.sort_values(by='Porcentagem de Nulos')

            Porcentagem de Nulos
MORB_DESC              81.270014
DOSE_2REF              82.651891
FAB_COVRF2             82.680380
LOTE_REF2              82.691919
DT_SAIDUTI             84.037014
...                          ...
PAIS_VGM              100.000000
DT_TRT_COV            100.000000
DT_VGM                100.000000
VG_REINF              100.000000
TABAG                 100.000000

[84 rows x 1 columns]

In [49]:
# Cria um gráfico de barras

null_count = (df.isnull().mean()* 100).sort_values(ascending=False)

plt.figure(figsize=(10, 6))
null_count.plot(kind='bar', color='skyblue')
plt.title('Porcentagem de valores nulos em cada coluna')
plt.xlabel('Colunas')
plt.ylabel('Quantidade de Valores Nulos')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

KeyboardInterrupt:

removendo as colunas que tem mais de 80% dos dados nulos

In [ ]:
df_copied = df.copy()

null_percentage = df_copied.isnull().mean() * 100

# Seleciona as colunas com mais de 75% de valores nulos
columns_to_drop = null_percentage[null_percentage > 80].index.tolist()
# print(columns_to_drop)

df_copied.drop(columns=columns_to_drop, inplace=True)

In [ ]:
df_copied.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277304 entries, 0 to 277303
Columns: 106 entries, DT_NOTIFIC to REINF
dtypes: float64(55), int64(7), object(44)
memory usage: 224.3+ MB

In [ ]:
# Mostrando os valores unicos da coluna target do modelo
df_copied['CLASSI_FIN'].unique()

array([ 5.,  2.,  4.,  1., nan,  3.])

In [ ]:
# ------------||-------------------
# Mostrando os nulos da coluna target
df_copied['CLASSI_FIN'].isna().mean()

0.03891036551942994

In [ ]:
# Retirando os nulos da coluna de classificação final
df_filter = df_copied.dropna(subset=['CLASSI_FIN']).copy()

In [ ]:
df_filter.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 266514 entries, 0 to 277303
Columns: 106 entries, DT_NOTIFIC to REINF
dtypes: float64(55), int64(7), object(44)
memory usage: 217.6+ MB

In [ ]:
# Verificando para limpar os nulos
df_filter.isna().sum().sort_values(ascending=False)

POS_PCRFLU    200872
DT_ENTUTI     196842
POS_PCROUT    193916
OUTRO_DES     190998
PUERPERA      189156
               ...
FATOR_RISC         0
SEM_NOT            0
HISTO_VGM          0
DT_DIGITA          0
DT_NOTIFIC         0
Length: 106, dtype: int64

Removendo as linhas inteiramente nulas

In [ ]:
df_filter.dropna(how='all', inplace=True)
df_filter.isna().sum().sort_values(ascending=False)

POS_PCRFLU    200872
DT_ENTUTI     196842
POS_PCROUT    193916
OUTRO_DES     190998
PUERPERA      189156
               ...
FATOR_RISC         0
SEM_NOT            0
HISTO_VGM          0
DT_DIGITA          0
DT_NOTIFIC         0
Length: 106, dtype: int64

In [ ]:
df_filter.info(max_cols=107)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 266514 entries, 0 to 277303
Data columns (total 106 columns):
 #    Column      Non-Null Count   Dtype
---   ------      --------------   -----
 0    DT_NOTIFIC  266514 non-null  object
 1    SEM_NOT     266514 non-null  int64
 2    DT_SIN_PRI  266514 non-null  object
 3    SEM_PRI     266514 non-null  int64
 4    SG_UF_NOT   266514 non-null  object
 5    ID_REGIONA  232597 non-null  object
 6    CO_REGIONA  232597 non-null  float64
 7    ID_MUNICIP  266514 non-null  object
 8    CO_MUN_NOT  266514 non-null  int64
 9    ID_UNIDADE  266514 non-null  object
 10   CO_UNI_NOT  266514 non-null  int64
 11   CS_SEXO     266514 non-null  object
 12   DT_NASC     266433 non-null  object
 13   NU_IDADE_N  266514 non-null  int64
 14   TP_IDADE    266514 non-null  int64
 15   COD_IDADE   266514 non-null  object
 16   CS_GESTANT  266514 non-null  int64
 17   CS_RACA     266514 non-null  float64
 18   CS_ESCOL_N  172044 non-null  object
 19   ID_PAIS     266514 non-null  object
 20   CO_PAIS     266514 non-null  object
 21   SG_UF       266447 non-null  object
 22   ID_RG_RESI  235462 non-null  object
 23   CO_RG_RESI  235462 non-null  object
 24   ID_MN_RESI  266447 non-null  object
 25   CO_MUN_RES  266447 non-null  float64
 26   CS_ZONA     245377 non-null  float64
 27   SURTO_SG    168134 non-null  float64
 28   NOSOCOMIAL  237133 non-null  float64
 29   AVE_SUINO   226877 non-null  float64
 30   FEBRE       229926 non-null  float64
 31   TOSSE       243377 non-null  float64
 32   GARGANTA    193409 non-null  float64
 33   DISPNEIA    232035 non-null  float64
 34   DESC_RESP   225157 non-null  float64
 35   SATURACAO   219706 non-null  float64
 36   DIARREIA    191998 non-null  float64
 37   VOMITO      194130 non-null  float64
 38   OUTRO_SIN   189795 non-null  float64
 39   OUTRO_DES   75516 non-null   object
 40   PUERPERA    77358 non-null   float64
 41   FATOR_RISC  266514 non-null  float64
 42   CARDIOPATI  91943 non-null   float64
 43   HEMATOLOGI  78670 non-null   float64
 44   SIND_DOWN   78323 non-null   float64
 45   HEPATICA    78133 non-null   float64
 46   ASMA        83260 non-null   float64
 47   DIABETES    86566 non-null   float64
 48   NEUROLOGIC  81985 non-null   float64
 49   PNEUMOPATI  81699 non-null   float64
 50   IMUNODEPRE  80577 non-null   float64
 51   RENAL       79477 non-null   float64
 52   OBESIDADE   78065 non-null   float64
 53   OUT_MORBI   91845 non-null   float64
 54   VACINA      145153 non-null  float64
 55   ANTIVIRAL   218522 non-null  float64
 56   HOSPITAL    260420 non-null  float64
 57   DT_INTERNA  252322 non-null  object
 58   SG_UF_INTE  246247 non-null  object
 59   ID_RG_INTE  214667 non-null  object
 60   CO_RG_INTE  214667 non-null  object
 61   ID_MN_INTE  246247 non-null  object
 62   CO_MU_INTE  246247 non-null  object
 63   UTI         236234 non-null  float64
 64   DT_ENTUTI   69672 non-null   object
 65   SUPORT_VEN  235007 non-null  float64
 66   RAIOX_RES   177447 non-null  object
 67   DT_RAIOX    98418 non-null   object
 68   AMOSTRA     261194 non-null  float64
 69   DT_COLETA   250132 non-null  object
 70   TP_AMOSTRA  246195 non-null  float64
 71   PCR_RESUL   246439 non-null  float64
 72   DT_PCR      180963 non-null  object
 73   POS_PCRFLU  65642 non-null   float64
 74   POS_PCROUT  72598 non-null   float64
 75   CLASSI_FIN  266514 non-null  float64
 76   CRITERIO    257868 non-null  float64
 77   EVOLUCAO    255947 non-null  object
 78   DT_EVOLUCA  236988 non-null  object
 79   DT_ENCERRA  255288 non-null  object
 80   DT_DIGITA   266514 non-null  object
 81   HISTO_VGM   266514 non-null  float64
 82   DOR_ABD     189751 non-null  float64
 83   FADIGA      194908 non-null  float64
 84   PERD_OLFT   187369 non-null  float64
 85   PERD_PALA   187190 non-null  float64
 86   TOMO_RES    161964 non-null  float64
 87   TP_TES_AN   117198 non-null  object
 88   DT_RES_AN   118532 non-null  object
 89   RES_AN      239577 non-null  float64
 90   ESTRANG     245937 non-null  float64
 91   VACINA_COV  266465 non-null  float64
 92   DOSE_1_COV  131679 non-null  object
 93   DOSE_2_COV  119990 non-null  object
 94   DOSE_REF    80293 non-null   object
 95   FAB_COV_1   131466 non-null  object
 96   FAB_COV_2   119826 non-null  object
 97   FAB_COVREF  80157 non-null   object
 98   LAB_PR_COV  131466 non-null  object
 99   LOTE_1_COV  131020 non-null  object
 100  LOTE_2_COV  119436 non-null  object
 101  LOTE_REF    79902 non-null   object
 102  FNT_IN_COV  266514 non-null  float64
 103  TRAT_COV    201979 non-null  float64
 104  CO_DETEC    158185 non-null  float64
 105  REINF       258030 non-null  float64
dtypes: float64(55), int64(7), object(44)
memory usage: 217.6+ MB

In [ ]:
# Quantidade de linhas duplicadas
df_filter.duplicated().sum()

190

Removendo as linhas duplicadas

In [ ]:
df_filter.drop_duplicates(inplace=True)

### Tratando as colunas

Ajustando as colunas que tem dados 2.0, 1.0 e 9.0 para -> 1.0 e 0.0

In [ ]:

list_colunas_tratar = [
'PUERPERA', 'SURTO_SG', 'GARGANTA', 'DIARREIA', 'VOMITO',
'CARDIOPATI', 'HEMATOLOGI', 'SIND_DOWN', 'HEPATICA', 'ASMA',
'DIABETES', 'NEUROLOGIC', 'PNEUMOPATI', 'IMUNODEPRE', 'RENAL',
'OBESIDADE', 'OUT_MORBI', 'VACINA', 'ANTIVIRAL',
'POS_PCRFLU', 'POS_PCROUT', 'DOR_ABD', 'FADIGA', 'PERD_OLFT',
'PERD_PALA', 'TRAT_COV', 'CO_DETEC', 'CS_ESCOL_N', 'ESTRANG',
'RES_AN', 'TP_TES_AN', 'TOMO_RES']


for i in list_colunas_tratar:
    
    try:
        frequencia = df_filter[i].value_counts()

        total_registros = df_filter[i].count()


        porcentagens = (frequencia / total_registros) * 100

        print(f'\n\nPorcentagens -- {i}  - \n{porcentagens}:\n')


        # Colocando os valores de 2 para o e NAN para 0
        df_filter[i].replace(6.0, 9, inplace=True)

        # Dentro dos NAN vão ser adicionados como casos que não eram PUERPERAS
        df_filter[i].fillna(value=9, inplace=True)
        print('\n\n',df_filter[i].describe())

        #Agora 1 é para quandor for PUERPERA e 0 quando não for, mantemos a quantidade de dados.
    except:
        print(f'Coluna que deu errada: {i}')

Porcentagens -- PUERPERA  -
2.0    97.988825
9.0     1.157557
1.0     0.853618
Name: PUERPERA, dtype: float64:



 count    266324.000000
mean          6.988837
std           3.170683
min           1.000000
25%           2.000000
50%           9.000000
75%           9.000000
max           9.000000
Name: PUERPERA, dtype: float64


Porcentagens -- SURTO_SG  -
2.0    84.791420
9.0     9.715088
1.0     5.493492
Name: SURTO_SG, dtype: float64:



 count    266324.000000
mean          4.978252
std           3.500726
min           1.000000
25%           2.000000
50%           2.000000
75%           9.000000
max           9.000000
Name: SURTO_SG, dtype: float64


Porcentagens -- GARGANTA  -
2.0    81.679393
1.0    15.318993
9.0     3.001614
Name: GARGANTA, dtype: float64:



 count    266324.000000
mean          3.960766
std           3.281809
min           1.000000
25%           2.000000
50%           2.000000
75%           9.000000
max           9.000000
Name: GARGANTA, dtype: float64


Porcentagens -- DIARREIA  -
2.0    87.962456
1.0    10.725807
9.0     1.311737
Name: DIARREIA, dtype: float64:



 count    266324.000000
mean          3.945469
std           3.232908
min           1.000000
25%           2.000000
50%           2.000000
75%           9.000000
max           9.000000
Name: DIARREIA, dtype: float64


Porcentagens -- VOMITO  -
2.0    83.050454
1.0    15.658937
9.0     1.290609
Name: VOMITO, dtype: float64:



 count    266324.000000
mean          3.852240
std           3.232264
min           1.000000
25%           2.000000
50%           2.000000
75%           9.000000
max           9.000000
Name: VOMITO, dtype: float64


Porcentagens -- CARDIOPATI  -
2.0    50.658947
1.0    48.511791
9.0     0.829261
Name: CARDIOPATI, dtype: float64:



 count    266324.000000
mean          6.437460
std           3.565143
min           1.000000
25%           2.000000
50%           9.000000
75%           9.000000
max           9.000000
Name: CARDIOPATI, dtype: float64


Porcentagens -- HEMATOLOGI  -
2.0    95.275220
1.0     3.407183
9.0     1.317597
Name: HEMATOLOGI, dtype: float64:



 count    266324.000000
mean          6.950530
std           3.197886
min           1.000000
25%           2.000000
50%           9.000000
75%           9.000000
max           9.000000
Name: HEMATOLOGI, dtype: float64


Porcentagens -- SIND_DOWN  -
2.0    96.358085
1.0     2.506291
9.0     1.135623
Name: SIND_DOWN, dtype: float64:



 count    266324.000000
mean          6.958427
std           3.190919
min           1.000000
25%           2.000000
50%           9.000000
75%           9.000000
max           9.000000
Name: SIND_DOWN, dtype: float64


Porcentagens -- HEPATICA  -
2.0    96.381145
1.0     2.310125
9.0     1.308730
Name: HEPATICA, dtype: float64:



 count    266324.000000
mean          6.967562
std           3.185983
min           1.000000
25%           2.000000
50%           9.000000
75%           9.000000
max           9.000000
Name: HEPATICA, dtype: float64


Porcentagens -- ASMA  -
2.0    77.284307
1.0    21.637827
9.0     1.077866
Name: ASMA, dtype: float64:



 count    266324.000000
mean          6.768628
std           3.343880
min           1.000000
25%           2.000000
50%           9.000000
75%           9.000000
max           9.000000
Name: ASMA, dtype: float64


Porcentagens -- DIABETES  -
2.0    67.490811
1.0    31.636498
9.0     0.872691
Name: DIABETES, dtype: float64:



 count    266324.000000
mean          6.643160
std           3.430071
min           1.000000
25%           2.000000
50%           9.000000
75%           9.000000
max           9.000000
Name: DIABETES, dtype: float64


Porcentagens -- NEUROLOGIC  -
2.0    82.169313
1.0    16.703074
9.0     1.127613
Name: NEUROLOGIC, dtype: float64:



 count    266324.000000
mean          6.819123
std           3.304708
min           1.000000
25%           2.000000
50%           9.000000
75%           9.000000
max           9.000000
Name: NEUROLOGIC, dtype: float64


Porcentagens -- PNEUMOPATI  -
2.0    81.936092
1.0    16.845277
9.0     1.218631
Name: PNEUMOPATI, dtype: float64:



 count    266324.000000
mean          6.828465
std           3.301268
min           1.000000
25%           2.000000
50%           9.000000
75%           9.000000
max           9.000000
Name: PNEUMOPATI, dtype: float64


Porcentagens -- IMUNODEPRE  -
2.0    88.622338
1.0    10.117340
9.0     1.260322
Name: IMUNODEPRE, dtype: float64:



 count    266324.000000
mean          6.879320
std           3.254577
min           1.000000
25%           2.000000
50%           9.000000
75%           9.000000
max           9.000000
Name: IMUNODEPRE, dtype: float64


Porcentagens -- RENAL  -
2.0    90.089761
1.0     8.719298
9.0     1.190941
Name: RENAL, dtype: float64:



 count    266324.000000
mean          6.911059
std           3.235274
min           1.000000
25%           2.000000
50%           9.000000
75%           9.000000
max           9.000000
Name: RENAL, dtype: float64


Porcentagens -- OBESIDADE  -
2.0    90.639700
1.0     7.627434
9.0     1.732867
Name: OBESIDADE, dtype: float64:



 count    266324.000000
mean          6.962504
std           3.207784
min           1.000000
25%           2.000000
50%           9.000000
75%           9.000000
max           9.000000
Name: OBESIDADE, dtype: float64


Porcentagens -- OUT_MORBI  -
1.0    55.792191
2.0    43.204497
9.0     1.003312
Name: OUT_MORBI, dtype: float64:



 count    266324.000000
mean          6.419159
std           3.597725
min           1.000000
25%           2.000000
50%           9.000000
75%           9.000000
max           9.000000
Name: OUT_MORBI, dtype: float64


Porcentagens -- VACINA  -
9.0    48.698014
2.0    38.899687
1.0    12.402299
Name: VACINA, dtype: float64:



 count    266324.000000
mean          6.976082
std           3.257566
min           1.000000
25%           2.000000
50%           9.000000
75%           9.000000
max           9.000000
Name: VACINA, dtype: float64


Porcentagens -- ANTIVIRAL  -
2.0    80.636743
9.0    11.621434
1.0     7.741823
Name: ANTIVIRAL, dtype: float64:



 count    266324.000000
mean          3.862686
std           3.174460
min           1.000000
25%           2.000000
50%           2.000000
75%           9.000000
max           9.000000
Name: ANTIVIRAL, dtype: float64


Porcentagens -- POS_PCRFLU  -
2.0    85.027064
1.0    13.548830
9.0     1.424106
Name: POS_PCRFLU, dtype: float64:



 count    266324.000000
mean          7.267362
std           3.064864
min           1.000000
25%           9.000000
50%           9.000000
75%           9.000000
max           9.000000
Name: POS_PCRFLU, dtype: float64


Porcentagens -- POS_PCROUT  -
1.0    91.344152
2.0     8.592425
9.0     0.063423
Name: POS_PCROUT, dtype: float64:



 count    266324.000000
mean          6.846112
std           3.525353
min           1.000000
25%           2.000000
50%           9.000000
75%           9.000000
max           9.000000
Name: POS_PCROUT, dtype: float64


Porcentagens -- DOR_ABD  -
2.0    89.301497
1.0     8.015968
9.0     2.682536
Name: DOR_ABD, dtype: float64:



 count    266324.000000
mean          4.092331
std           3.274924
min           1.000000
25%           2.000000
50%           2.000000
75%           9.000000
max           9.000000
Name: DOR_ABD, dtype: float64


Porcentagens -- FADIGA  -
2.0    75.987844
1.0    21.921219
9.0     2.090938
Name: FADIGA, dtype: float64:



 count    266324.000000
mean          3.826824
std           3.276156
min           1.000000
25%           2.000000
50%           2.000000
75%           9.000000
max           9.000000
Name: FADIGA, dtype: float64


Porcentagens -- PERD_OLFT  -
2.0    94.039647
9.0     4.289895
1.0     1.670458
Name: PERD_OLFT, dtype: float64:



 count    266324.000000
mean          4.277651
std           3.293913
min           1.000000
25%           2.000000
50%           2.000000
75%           9.000000
max           9.000000
Name: PERD_OLFT, dtype: float64


Porcentagens -- PERD_PALA  -
2.0    94.087933
9.0     4.303087
1.0     1.608980
Name: PERD_PALA, dtype: float64:



 count    266324.000000
mean          4.283245
std           3.295446
min           1.000000
25%           2.000000
50%           2.000000
75%           9.000000
max           9.000000
Name: PERD_PALA, dtype: float64


Porcentagens -- TRAT_COV  -
2.0    83.726102
9.0    14.942051
1.0     1.331847
Name: TRAT_COV, dtype: float64:



 count    266324.000000
mean          4.476138
std           3.358947
min           1.000000
25%           2.000000
50%           2.000000
75%           9.000000
max           9.000000
Name: TRAT_COV, dtype: float64


Porcentagens -- CO_DETEC  -
2.0    86.571016
9.0    11.335054
1.0     2.093930
Name: CO_DETEC, dtype: float64:



 count    266324.000000
mean          5.303690
std           3.508694
min           1.000000
25%           2.000000
50%           2.000000
75%           9.000000
max           9.000000
Name: CO_DETEC, dtype: float64


Porcentagens -- CS_ESCOL_N  -
9.0    35.479031
5.0    25.958323
1.0    12.563612
0.0    10.883384
3.0     6.014272
2.0     5.086629
4.0     2.543314
9       0.501335
5       0.390250
1       0.199487
0       0.166336
2       0.090147
3       0.087239
4       0.036640
Name: CS_ESCOL_N, dtype: float64:



 count     266324.0
unique        14.0
top            9.0
freq      155386.0
Name: CS_ESCOL_N, dtype: float64


Porcentagens -- ESTRANG  -
2.0    99.22815
1.0     0.77185
Name: ESTRANG, dtype: float64:



 count    266324.000000
mean          2.533035
std           1.871928
min           1.000000
25%           2.000000
50%           2.000000
75%           2.000000
max           9.000000
Name: ESTRANG, dtype: float64


Porcentagens -- RES_AN  -
5.0    32.955158
2.0    32.577539
4.0    18.385931
1.0    15.611019
9.0     0.438606
3.0     0.031747
Name: RES_AN, dtype: float64:



 count    266324.000000
mean          3.814579
std           2.307126
min           1.000000
25%           2.000000
50%           4.000000
75%           5.000000
max           9.000000
Name: RES_AN, dtype: float64


Porcentagens -- TP_TES_AN  -
2.0    94.542599
1.0     4.008126
2       1.380994
1       0.068282
Name: TP_TES_AN, dtype: float64:



 count     266324
unique         5
top            9
freq      149162
Name: TP_TES_AN, dtype: int64


Porcentagens -- TOMO_RES  -
6.0    71.732739
9.0     8.548804
5.0     6.695739
1.0     5.564135
2.0     3.869198
3.0     2.961197
4.0     0.628189
Name: TOMO_RES, dtype: float64:



 count    266324.000000
mean          8.274864
std           2.045999
min           1.000000
25%           9.000000
50%           9.000000
75%           9.000000
max           9.000000
Name: TOMO_RES, dtype: float64

In [ ]:
df_filter.info(max_cols=107)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 266324 entries, 0 to 277303
Data columns (total 106 columns):
 #    Column      Non-Null Count   Dtype
---   ------      --------------   -----
 0    DT_NOTIFIC  266324 non-null  object
 1    SEM_NOT     266324 non-null  int64
 2    DT_SIN_PRI  266324 non-null  object
 3    SEM_PRI     266324 non-null  int64
 4    SG_UF_NOT   266324 non-null  object
 5    ID_REGIONA  232439 non-null  object
 6    CO_REGIONA  232439 non-null  float64
 7    ID_MUNICIP  266324 non-null  object
 8    CO_MUN_NOT  266324 non-null  int64
 9    ID_UNIDADE  266324 non-null  object
 10   CO_UNI_NOT  266324 non-null  int64
 11   CS_SEXO     266324 non-null  object
 12   DT_NASC     266243 non-null  object
 13   NU_IDADE_N  266324 non-null  int64
 14   TP_IDADE    266324 non-null  int64
 15   COD_IDADE   266324 non-null  object
 16   CS_GESTANT  266324 non-null  int64
 17   CS_RACA     266324 non-null  float64
 18   CS_ESCOL_N  266324 non-null  object
 19   ID_PAIS     266324 non-null  object
 20   CO_PAIS     266324 non-null  object
 21   SG_UF       266257 non-null  object
 22   ID_RG_RESI  235306 non-null  object
 23   CO_RG_RESI  235306 non-null  object
 24   ID_MN_RESI  266257 non-null  object
 25   CO_MUN_RES  266257 non-null  float64
 26   CS_ZONA     245216 non-null  float64
 27   SURTO_SG    266324 non-null  float64
 28   NOSOCOMIAL  236996 non-null  float64
 29   AVE_SUINO   226749 non-null  float64
 30   FEBRE       229788 non-null  float64
 31   TOSSE       243226 non-null  float64
 32   GARGANTA    266324 non-null  float64
 33   DISPNEIA    231890 non-null  float64
 34   DESC_RESP   225020 non-null  float64
 35   SATURACAO   219572 non-null  float64
 36   DIARREIA    266324 non-null  float64
 37   VOMITO      266324 non-null  float64
 38   OUTRO_SIN   189712 non-null  float64
 39   OUTRO_DES   75473 non-null   object
 40   PUERPERA    266324 non-null  float64
 41   FATOR_RISC  266324 non-null  float64
 42   CARDIOPATI  266324 non-null  float64
 43   HEMATOLOGI  266324 non-null  float64
 44   SIND_DOWN   266324 non-null  float64
 45   HEPATICA    266324 non-null  float64
 46   ASMA        266324 non-null  float64
 47   DIABETES    266324 non-null  float64
 48   NEUROLOGIC  266324 non-null  float64
 49   PNEUMOPATI  266324 non-null  float64
 50   IMUNODEPRE  266324 non-null  float64
 51   RENAL       266324 non-null  float64
 52   OBESIDADE   266324 non-null  float64
 53   OUT_MORBI   266324 non-null  float64
 54   VACINA      266324 non-null  float64
 55   ANTIVIRAL   266324 non-null  float64
 56   HOSPITAL    260268 non-null  float64
 57   DT_INTERNA  252180 non-null  object
 58   SG_UF_INTE  246099 non-null  object
 59   ID_RG_INTE  214529 non-null  object
 60   CO_RG_INTE  214529 non-null  object
 61   ID_MN_INTE  246099 non-null  object
 62   CO_MU_INTE  246099 non-null  object
 63   UTI         236077 non-null  float64
 64   DT_ENTUTI   69606 non-null   object
 65   SUPORT_VEN  234869 non-null  float64
 66   RAIOX_RES   177360 non-null  object
 67   DT_RAIOX    98370 non-null   object
 68   AMOSTRA     261010 non-null  float64
 69   DT_COLETA   249950 non-null  object
 70   TP_AMOSTRA  246027 non-null  float64
 71   PCR_RESUL   246261 non-null  float64
 72   DT_PCR      180817 non-null  object
 73   POS_PCRFLU  266324 non-null  float64
 74   POS_PCROUT  266324 non-null  float64
 75   CLASSI_FIN  266324 non-null  float64
 76   CRITERIO    257696 non-null  float64
 77   EVOLUCAO    255772 non-null  object
 78   DT_EVOLUCA  236839 non-null  object
 79   DT_ENCERRA  255106 non-null  object
 80   DT_DIGITA   266324 non-null  object
 81   HISTO_VGM   266324 non-null  float64
 82   DOR_ABD     266324 non-null  float64
 83   FADIGA      266324 non-null  float64
 84   PERD_OLFT   266324 non-null  float64
 85   PERD_PALA   266324 non-null  float64
 86   TOMO_RES    266324 non-null  float64
 87   TP_TES_AN   266324 non-null  object
 88   DT_RES_AN   118432 non-null  object
 89   RES_AN      266324 non-null  float64
 90   ESTRANG     266324 non-null  float64
 91   VACINA_COV  266275 non-null  float64
 92   DOSE_1_COV  131581 non-null  object
 93   DOSE_2_COV  119904 non-null  object
 94   DOSE_REF    80227 non-null   object
 95   FAB_COV_1   131368 non-null  object
 96   FAB_COV_2   119740 non-null  object
 97   FAB_COVREF  80091 non-null   object
 98   LAB_PR_COV  131368 non-null  object
 99   LOTE_1_COV  130922 non-null  object
 100  LOTE_2_COV  119350 non-null  object
 101  LOTE_REF    79836 non-null   object
 102  FNT_IN_COV  266324 non-null  float64
 103  TRAT_COV    266324 non-null  float64
 104  CO_DETEC    266324 non-null  float64
 105  REINF       257840 non-null  float64
dtypes: float64(55), int64(7), object(44)
memory usage: 217.4+ MB

Criando a coluna coriza a partir da coluna Outro_sin

In [ ]:
# Adicione uma nova coluna 'Coriza' com valor padrão como 0
df_filter['Coriza'] = 0

df_filter['OUTRO_DES'].fillna(value='sem sintomas', inplace=True)

# Verifique se a string 'coriza' está presente em 'outro_sin' e atualize 'Coriza' para 1
df_filter.loc[df_filter['OUTRO_DES'].str.contains('CORIZA', case=False), 'Coriza'] = 1

In [ ]:
df_filter[['Coriza', 'OUTRO_DES']].head(50)

# Criado uma coluna somente para a Coriza que é um sintoma importante no caso de gripes

    Coriza                       OUTRO_DES
0        0                    sem sintomas
1        0                    sem sintomas
2        0                    sem sintomas
3        0                    sem sintomas
4        0                    sem sintomas
5        0                    sem sintomas
6        0                     CHEGA EM VM
7        0                    sem sintomas
8        0                    sem sintomas
9        0                    sem sintomas
10       0                    sem sintomas
11       0                    sem sintomas
12       0                    sem sintomas
13       1          CORIZA CONGESTAO NASAL
15       0                    sem sintomas
16       1                          CORIZA
17       0                    sem sintomas
18       0                    DOR TORACICA
19       0                    sem sintomas
20       0                    sem sintomas
21       0                    sem sintomas
22       0                    sem sintomas
23       0                    sem sintomas
24       0                    sem sintomas
25       0                    sem sintomas
26       0                    sem sintomas
27       0                      HIPOTENSAO
28       0                    sem sintomas
29       1                          CORIZA
30       0       INAPETENCIA, TSC, CIANOSE
31       0                    sem sintomas
32       0                    sem sintomas
34       0                    sem sintomas
35       1                          CORIZA
36       0                    sem sintomas
37       0                    sem sintomas
38       0                    sem sintomas
39       0                    sem sintomas
40       0                    sem sintomas
41       0                    sem sintomas
42       0                    sem sintomas
43       0                    sem sintomas
44       0                    sem sintomas
45       0                    sem sintomas
46       0                    sem sintomas
47       0  ASTENIA,CALAFRIOS,TOSSE PRODUT
48       0                    sem sintomas
49       1                          CORIZA
50       0                   ASSINTOMATICO
51       0                    sem sintomas

In [ ]:
# Quantidade de vezes que o sintoma coriza apareceu.
df_filter['Coriza'].sum()

26832

Removendo as colunas de outros sintomas, por não sabermos que outros sintomas são esses

In [ ]:
# removido as colunas de outros sintomas                                                                                                                                   as duas colunas por conta de não terem dados que ajudem na analise
df_filter.drop(columns=['OUTRO_DES', 'OUTRO_SIN'], inplace=True)

In [ ]:
df_filter.info(max_cols=107)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 266324 entries, 0 to 277303
Data columns (total 105 columns):
 #    Column      Non-Null Count   Dtype
---   ------      --------------   -----
 0    DT_NOTIFIC  266324 non-null  object
 1    SEM_NOT     266324 non-null  int64
 2    DT_SIN_PRI  266324 non-null  object
 3    SEM_PRI     266324 non-null  int64
 4    SG_UF_NOT   266324 non-null  object
 5    ID_REGIONA  232439 non-null  object
 6    CO_REGIONA  232439 non-null  float64
 7    ID_MUNICIP  266324 non-null  object
 8    CO_MUN_NOT  266324 non-null  int64
 9    ID_UNIDADE  266324 non-null  object
 10   CO_UNI_NOT  266324 non-null  int64
 11   CS_SEXO     266324 non-null  object
 12   DT_NASC     266243 non-null  object
 13   NU_IDADE_N  266324 non-null  int64
 14   TP_IDADE    266324 non-null  int64
 15   COD_IDADE   266324 non-null  object
 16   CS_GESTANT  266324 non-null  int64
 17   CS_RACA     266324 non-null  float64
 18   CS_ESCOL_N  266324 non-null  object
 19   ID_PAIS     266324 non-null  object
 20   CO_PAIS     266324 non-null  object
 21   SG_UF       266257 non-null  object
 22   ID_RG_RESI  235306 non-null  object
 23   CO_RG_RESI  235306 non-null  object
 24   ID_MN_RESI  266257 non-null  object
 25   CO_MUN_RES  266257 non-null  float64
 26   CS_ZONA     245216 non-null  float64
 27   SURTO_SG    266324 non-null  float64
 28   NOSOCOMIAL  236996 non-null  float64
 29   AVE_SUINO   226749 non-null  float64
 30   FEBRE       229788 non-null  float64
 31   TOSSE       243226 non-null  float64
 32   GARGANTA    266324 non-null  float64
 33   DISPNEIA    231890 non-null  float64
 34   DESC_RESP   225020 non-null  float64
 35   SATURACAO   219572 non-null  float64
 36   DIARREIA    266324 non-null  float64
 37   VOMITO      266324 non-null  float64
 38   PUERPERA    266324 non-null  float64
 39   FATOR_RISC  266324 non-null  float64
 40   CARDIOPATI  266324 non-null  float64
 41   HEMATOLOGI  266324 non-null  float64
 42   SIND_DOWN   266324 non-null  float64
 43   HEPATICA    266324 non-null  float64
 44   ASMA        266324 non-null  float64
 45   DIABETES    266324 non-null  float64
 46   NEUROLOGIC  266324 non-null  float64
 47   PNEUMOPATI  266324 non-null  float64
 48   IMUNODEPRE  266324 non-null  float64
 49   RENAL       266324 non-null  float64
 50   OBESIDADE   266324 non-null  float64
 51   OUT_MORBI   266324 non-null  float64
 52   VACINA      266324 non-null  float64
 53   ANTIVIRAL   266324 non-null  float64
 54   HOSPITAL    260268 non-null  float64
 55   DT_INTERNA  252180 non-null  object
 56   SG_UF_INTE  246099 non-null  object
 57   ID_RG_INTE  214529 non-null  object
 58   CO_RG_INTE  214529 non-null  object
 59   ID_MN_INTE  246099 non-null  object
 60   CO_MU_INTE  246099 non-null  object
 61   UTI         236077 non-null  float64
 62   DT_ENTUTI   69606 non-null   object
 63   SUPORT_VEN  234869 non-null  float64
 64   RAIOX_RES   177360 non-null  object
 65   DT_RAIOX    98370 non-null   object
 66   AMOSTRA     261010 non-null  float64
 67   DT_COLETA   249950 non-null  object
 68   TP_AMOSTRA  246027 non-null  float64
 69   PCR_RESUL   246261 non-null  float64
 70   DT_PCR      180817 non-null  object
 71   POS_PCRFLU  266324 non-null  float64
 72   POS_PCROUT  266324 non-null  float64
 73   CLASSI_FIN  266324 non-null  float64
 74   CRITERIO    257696 non-null  float64
 75   EVOLUCAO    255772 non-null  object
 76   DT_EVOLUCA  236839 non-null  object
 77   DT_ENCERRA  255106 non-null  object
 78   DT_DIGITA   266324 non-null  object
 79   HISTO_VGM   266324 non-null  float64
 80   DOR_ABD     266324 non-null  float64
 81   FADIGA      266324 non-null  float64
 82   PERD_OLFT   266324 non-null  float64
 83   PERD_PALA   266324 non-null  float64
 84   TOMO_RES    266324 non-null  float64
 85   TP_TES_AN   266324 non-null  object
 86   DT_RES_AN   118432 non-null  object
 87   RES_AN      266324 non-null  float64
 88   ESTRANG     266324 non-null  float64
 89   VACINA_COV  266275 non-null  float64
 90   DOSE_1_COV  131581 non-null  object
 91   DOSE_2_COV  119904 non-null  object
 92   DOSE_REF    80227 non-null   object
 93   FAB_COV_1   131368 non-null  object
 94   FAB_COV_2   119740 non-null  object
 95   FAB_COVREF  80091 non-null   object
 96   LAB_PR_COV  131368 non-null  object
 97   LOTE_1_COV  130922 non-null  object
 98   LOTE_2_COV  119350 non-null  object
 99   LOTE_REF    79836 non-null   object
 100  FNT_IN_COV  266324 non-null  float64
 101  TRAT_COV    266324 non-null  float64
 102  CO_DETEC    266324 non-null  float64
 103  REINF       257840 non-null  float64
 104  Coriza      266324 non-null  int64
dtypes: float64(54), int64(8), object(43)
memory usage: 215.4+ MB

In [ ]:
# Verificando essas colunas

lista_colunas_analise = [
    'RAIOX_RES', 'DT_RAIOX', 'DT_PCR', 'DT_EVOLUCA', 'DOSE_1_COV', 'DOSE_2_COV', 'DOSE_REF', 'FAB_COV_1',
    'FAB_COV_2', 'FAB_COVREF', 'LAB_PR_COV', 'LOTE_1_COV', 'LOTE_2_COV', 'LOTE_REF'
]


for i in lista_colunas_analise:
    
    try:
        frequencia = df_filter[i].value_counts()

        total_registros = df_filter[i].count()


        porcentagens = (frequencia / total_registros) * 100

        print(f'\n\nPorcentagens -- {i}  - \n{porcentagens}:\n')

    except:
        print(f'Coluna que deu errada: {i}')

Porcentagens -- RAIOX_RES  -
6.0    29.532025
2.0    23.474290
5.0    13.973839
1.0    11.622124
9.0    10.862652
3.0     5.835025
4.0     3.183920
6       0.435837
2       0.368742
5       0.214253
1       0.175350
9       0.168020
3       0.100361
4       0.053563
Name: RAIOX_RES, dtype: float64:



Porcentagens -- DT_RAIOX  -
23/05/2023    0.502186
22/05/2023    0.494053
24/05/2023    0.493036
24/04/2023    0.491003
29/05/2023    0.477788
                ...
31/01/2024    0.001017
08/02/2024    0.001017
24/05/4202    0.001017
14/02/2202    0.001017
23/12/2202    0.001017
Name: DT_RAIOX, Length: 437, dtype: float64:



Porcentagens -- DT_PCR  -
07/06/2023    0.642639
30/05/2023    0.629366
18/05/2023    0.619964
25/05/2023    0.587334
02/06/2023    0.566318
                ...
05/02/2024    0.000553
18/02/2024    0.000553
07/02/2024    0.000553
28/01/2024    0.000553
09/02/2024    0.000553
Name: DT_PCR, Length: 404, dtype: float64:



Porcentagens -- DT_EVOLUCA  -
30/05/2023    0.516807
26/05/2023    0.492740
25/05/2023    0.475006
02/06/2023    0.469095
10/05/2023    0.463606
                ...
13/02/2024    0.002111
12/02/2024    0.000844
15/02/2024    0.000844
14/02/2024    0.000422
16/02/2024    0.000422
Name: DT_EVOLUCA, Length: 412, dtype: float64:



Porcentagens -- DOSE_1_COV  -
22/09/2021    2.621199
03/03/2021    1.431058
26/03/2021    1.356579
01/03/2021    1.313260
25/03/2021    1.279820
                ...
07/09/2022    0.000760
18/08/2020    0.000760
12/08/2023    0.000760
26/12/2023    0.000760
14/08/2022    0.000760
Name: DOSE_1_COV, Length: 1008, dtype: float64:



Porcentagens -- DOSE_2_COV  -
04/06/2021    3.318488
20/04/2021    1.236823
19/04/2021    1.218475
16/04/2021    1.164265
22/04/2021    1.158427
                ...
11/12/2023    0.000834
21/01/2021    0.000834
13/12/2023    0.000834
23/01/2022    0.000834
12/02/2023    0.000834
Name: DOSE_2_COV, Length: 983, dtype: float64:



Porcentagens -- DOSE_REF  -
27/10/2021    0.877510
26/10/2021    0.867538
28/10/2021    0.833884
04/11/2021    0.820173
14/10/2021    0.815187
                ...
21/02/2021    0.001246
08/05/2022    0.001246
18/10/2023    0.001246
24/10/2023    0.001246
14/11/2023    0.001246
Name: DOSE_REF, Length: 689, dtype: float64:



Porcentagens -- FAB_COV_1  -
86 - COVID-19 SINOVAC/BUTANTAN - CORONAVAC                      43.544851
85 - COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD                  30.362036
87 - COVID-19 PFIZER - COMIRNATY                                12.640065
102 - COVID-19 PFIZER - COMIRNATY PEDIATRICA MENOR DE 5 ANOS     4.947933
99 - COVID-19 PEDIATRICA - PFIZER COMIRNATY                      4.918245
                                                                  ...
215VCD150W                                                       0.000761
ASTRAZENECA/OXFORD                                               0.000761
ASTRAZANECA                                                      0.000761
VACINA COVID-19-RNAM, PFIZER (COMIRNATY)                         0.000761
PFIZER PFIZER PED                                                0.000761
Name: FAB_COV_1, Length: 194, dtype: float64:



Porcentagens -- FAB_COV_2  -
86 - COVID-19 SINOVAC/BUTANTAN - CORONAVAC                      47.820277
85 - COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD                  30.637214
87 - COVID-19 PFIZER - COMIRNATY                                10.446801
99 - COVID-19 PEDIATRICA - PFIZER COMIRNATY                      3.791548
102 - COVID-19 PFIZER - COMIRNATY PEDIATRICA MENOR DE 5 ANOS     2.872056
                                                                  ...
85- CIVUD-19 ASTRAZENECA                                         0.000835
99 - COVID-19 PEDIATRICA                                         0.000835
2151CD1697                                                       0.000835
210F21A                                                          0.000835
P/FIZER                                                          0.000835
Name: FAB_COV_2, Length: 174, dtype: float64:



Porcentagens -- FAB_COVREF  -
87 - COVID-19 PFIZER - COMIRNATY                  68.764281
88 - COVID-19 JANSSEN - AD26.COV2.S               11.832790
85 - COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD     9.401805
86 - COVID-19 SINOVAC/BUTANTAN - CORONAVAC         6.581264
103 - COVID-19 PFIZER - COMIRNATY BIVALENTE        1.379681
                                                    ...
PFIZER PEDRIATRICA                                 0.001249
PFIZER PEDIATRICA (DE 5 A 11 ANOS)                 0.001249
PFIZER (COMIRNATY) PEDIATRICA                      0.001249
PFIZER COMB.                                       0.001249
PFAZER-BIONTECH                                    0.001249
Name: FAB_COVREF, Length: 95, dtype: float64:



Porcentagens -- LAB_PR_COV  -
86 - COVID-19 SINOVAC/BUTANTAN - CORONAVAC                      43.544851
85 - COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD                  30.362036
87 - COVID-19 PFIZER - COMIRNATY                                12.640065
102 - COVID-19 PFIZER - COMIRNATY PEDIATRICA MENOR DE 5 ANOS     4.947933
99 - COVID-19 PEDIATRICA - PFIZER COMIRNATY                      4.918245
                                                                  ...
215VCD150W                                                       0.000761
ASTRAZENECA/OXFORD                                               0.000761
ASTRAZANECA                                                      0.000761
VACINA COVID-19-RNAM, PFIZER (COMIRNATY)                         0.000761
PFIZER PFIZER PED                                                0.000761
Name: LAB_PR_COV, Length: 194, dtype: float64:



Porcentagens -- LOTE_1_COV  -
GC9016          3.702204
FF8842          2.669528
4120Z026        2.576343
FP8290          2.438093
4120Z005        2.085211
                  ...
212VVD002ZVA    0.000764
GC9O16          0.000764
217VCD244W      0.000764
EW195           0.000764
213VCD014       0.000764
Name: LOTE_1_COV, Length: 1573, dtype: float64:



Porcentagens -- LOTE_2_COV  -
210223        3.276917
GC9016        1.830750
210130        1.164642
FR8392        0.956012
FP0362        0.954336
                ...
21OVCD347X    0.000838
214vcdo64z    0.000838
221VCD001X    0.000838
210018        0.000838
216VCD13VA    0.000838
Name: LOTE_2_COV, Length: 1561, dtype: float64:



Porcentagens -- LOTE_REF  -
FK8917        2.769427
202H21A       2.533945
FM3355        2.220803
FM3884        1.955258
FJ2594        1.942733
                ...
221VCDO18Z    0.001253
207F21A       0.001253
225vcd128w    0.001253
FM3886        0.001253
1f1062A       0.001253
Name: LOTE_REF, Length: 1002, dtype: float64:

In [ ]:
df_filter.info(max_cols=107)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 266324 entries, 0 to 277303
Data columns (total 105 columns):
 #    Column      Non-Null Count   Dtype
---   ------      --------------   -----
 0    DT_NOTIFIC  266324 non-null  object
 1    SEM_NOT     266324 non-null  int64
 2    DT_SIN_PRI  266324 non-null  object
 3    SEM_PRI     266324 non-null  int64
 4    SG_UF_NOT   266324 non-null  object
 5    ID_REGIONA  232439 non-null  object
 6    CO_REGIONA  232439 non-null  float64
 7    ID_MUNICIP  266324 non-null  object
 8    CO_MUN_NOT  266324 non-null  int64
 9    ID_UNIDADE  266324 non-null  object
 10   CO_UNI_NOT  266324 non-null  int64
 11   CS_SEXO     266324 non-null  object
 12   DT_NASC     266243 non-null  object
 13   NU_IDADE_N  266324 non-null  int64
 14   TP_IDADE    266324 non-null  int64
 15   COD_IDADE   266324 non-null  object
 16   CS_GESTANT  266324 non-null  int64
 17   CS_RACA     266324 non-null  float64
 18   CS_ESCOL_N  266324 non-null  object
 19   ID_PAIS     266324 non-null  object
 20   CO_PAIS     266324 non-null  object
 21   SG_UF       266257 non-null  object
 22   ID_RG_RESI  235306 non-null  object
 23   CO_RG_RESI  235306 non-null  object
 24   ID_MN_RESI  266257 non-null  object
 25   CO_MUN_RES  266257 non-null  float64
 26   CS_ZONA     245216 non-null  float64
 27   SURTO_SG    266324 non-null  float64
 28   NOSOCOMIAL  236996 non-null  float64
 29   AVE_SUINO   226749 non-null  float64
 30   FEBRE       229788 non-null  float64
 31   TOSSE       243226 non-null  float64
 32   GARGANTA    266324 non-null  float64
 33   DISPNEIA    231890 non-null  float64
 34   DESC_RESP   225020 non-null  float64
 35   SATURACAO   219572 non-null  float64
 36   DIARREIA    266324 non-null  float64
 37   VOMITO      266324 non-null  float64
 38   PUERPERA    266324 non-null  float64
 39   FATOR_RISC  266324 non-null  float64
 40   CARDIOPATI  266324 non-null  float64
 41   HEMATOLOGI  266324 non-null  float64
 42   SIND_DOWN   266324 non-null  float64
 43   HEPATICA    266324 non-null  float64
 44   ASMA        266324 non-null  float64
 45   DIABETES    266324 non-null  float64
 46   NEUROLOGIC  266324 non-null  float64
 47   PNEUMOPATI  266324 non-null  float64
 48   IMUNODEPRE  266324 non-null  float64
 49   RENAL       266324 non-null  float64
 50   OBESIDADE   266324 non-null  float64
 51   OUT_MORBI   266324 non-null  float64
 52   VACINA      266324 non-null  float64
 53   ANTIVIRAL   266324 non-null  float64
 54   HOSPITAL    260268 non-null  float64
 55   DT_INTERNA  252180 non-null  object
 56   SG_UF_INTE  246099 non-null  object
 57   ID_RG_INTE  214529 non-null  object
 58   CO_RG_INTE  214529 non-null  object
 59   ID_MN_INTE  246099 non-null  object
 60   CO_MU_INTE  246099 non-null  object
 61   UTI         236077 non-null  float64
 62   DT_ENTUTI   69606 non-null   object
 63   SUPORT_VEN  234869 non-null  float64
 64   RAIOX_RES   177360 non-null  object
 65   DT_RAIOX    98370 non-null   object
 66   AMOSTRA     261010 non-null  float64
 67   DT_COLETA   249950 non-null  object
 68   TP_AMOSTRA  246027 non-null  float64
 69   PCR_RESUL   246261 non-null  float64
 70   DT_PCR      180817 non-null  object
 71   POS_PCRFLU  266324 non-null  float64
 72   POS_PCROUT  266324 non-null  float64
 73   CLASSI_FIN  266324 non-null  float64
 74   CRITERIO    257696 non-null  float64
 75   EVOLUCAO    255772 non-null  object
 76   DT_EVOLUCA  236839 non-null  object
 77   DT_ENCERRA  255106 non-null  object
 78   DT_DIGITA   266324 non-null  object
 79   HISTO_VGM   266324 non-null  float64
 80   DOR_ABD     266324 non-null  float64
 81   FADIGA      266324 non-null  float64
 82   PERD_OLFT   266324 non-null  float64
 83   PERD_PALA   266324 non-null  float64
 84   TOMO_RES    266324 non-null  float64
 85   TP_TES_AN   266324 non-null  object
 86   DT_RES_AN   118432 non-null  object
 87   RES_AN      266324 non-null  float64
 88   ESTRANG     266324 non-null  float64
 89   VACINA_COV  266275 non-null  float64
 90   DOSE_1_COV  131581 non-null  object
 91   DOSE_2_COV  119904 non-null  object
 92   DOSE_REF    80227 non-null   object
 93   FAB_COV_1   131368 non-null  object
 94   FAB_COV_2   119740 non-null  object
 95   FAB_COVREF  80091 non-null   object
 96   LAB_PR_COV  131368 non-null  object
 97   LOTE_1_COV  130922 non-null  object
 98   LOTE_2_COV  119350 non-null  object
 99   LOTE_REF    79836 non-null   object
 100  FNT_IN_COV  266324 non-null  float64
 101  TRAT_COV    266324 non-null  float64
 102  CO_DETEC    266324 non-null  float64
 103  REINF       257840 non-null  float64
 104  Coriza      266324 non-null  int64
dtypes: float64(54), int64(8), object(43)
memory usage: 215.4+ MB

In [ ]:
# Removendo colunas que não devem fazer efeito para a analise
df_final = df_filter.copy()

In [ ]:
colunas_remover = ['RAIOX_RES', 'DT_RAIOX', 'DT_PCR', 'DT_EVOLUCA', 'DT_RES_AN',
                   'DOSE_1_COV', 'DOSE_2_COV', 'DOSE_REF', 'FAB_COVREF', 'DT_ENTUTI',
                   'FAB_COV_1', 'FAB_COV_2', 'LAB_PR_COV', 'LOTE_1_COV', 'LOTE_2_COV',
                   'LOTE_REF']

df_final.drop(columns=colunas_remover, axis=1, inplace=True)

In [59]:
df_final.info(max_cols=105)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 112215 entries, 1 to 277293
Data columns (total 89 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   DT_NOTIFIC  112215 non-null  object
 1   SEM_NOT     112215 non-null  int64
 2   DT_SIN_PRI  112215 non-null  object
 3   SEM_PRI     112215 non-null  int64
 4   SG_UF_NOT   112215 non-null  object
 5   ID_REGIONA  112215 non-null  object
 6   CO_REGIONA  112215 non-null  Int32
 7   ID_MUNICIP  112215 non-null  object
 8   CO_MUN_NOT  112215 non-null  int64
 9   ID_UNIDADE  112215 non-null  object
 10  CO_UNI_NOT  112215 non-null  int64
 11  CS_SEXO     112215 non-null  object
 12  DT_NASC     112215 non-null  object
 13  NU_IDADE_N  112215 non-null  int64
 14  TP_IDADE    112215 non-null  int64
 15  COD_IDADE   112215 non-null  object
 16  CS_GESTANT  112215 non-null  int64
 17  CS_RACA     112215 non-null  Int32
 18  CS_ESCOL_N  112215 non-null  Int32
 19  ID_PAIS     112215 non-null  object
 20  CO_PAIS     112215 non-null  object
 21  SG_UF       112215 non-null  object
 22  ID_RG_RESI  112215 non-null  object
 23  CO_RG_RESI  112215 non-null  object
 24  ID_MN_RESI  112215 non-null  object
 25  CO_MUN_RES  112215 non-null  Int32
 26  CS_ZONA     112215 non-null  Int32
 27  SURTO_SG    112215 non-null  Int32
 28  NOSOCOMIAL  112215 non-null  Int32
 29  AVE_SUINO   112215 non-null  Int32
 30  FEBRE       112215 non-null  Int32
 31  TOSSE       112215 non-null  Int32
 32  GARGANTA    112215 non-null  Int32
 33  DISPNEIA    112215 non-null  Int32
 34  DESC_RESP   112215 non-null  Int32
 35  SATURACAO   112215 non-null  Int32
 36  DIARREIA    112215 non-null  Int32
 37  VOMITO      112215 non-null  Int32
 38  PUERPERA    112215 non-null  Int32
 39  FATOR_RISC  112215 non-null  Int32
 40  CARDIOPATI  112215 non-null  Int32
 41  HEMATOLOGI  112215 non-null  Int32
 42  SIND_DOWN   112215 non-null  Int32
 43  HEPATICA    112215 non-null  Int32
 44  ASMA        112215 non-null  Int32
 45  DIABETES    112215 non-null  Int32
 46  NEUROLOGIC  112215 non-null  Int32
 47  PNEUMOPATI  112215 non-null  Int32
 48  IMUNODEPRE  112215 non-null  Int32
 49  RENAL       112215 non-null  Int32
 50  OBESIDADE   112215 non-null  Int32
 51  OUT_MORBI   112215 non-null  Int32
 52  VACINA      112215 non-null  Int32
 53  ANTIVIRAL   112215 non-null  Int32
 54  HOSPITAL    112215 non-null  Int32
 55  DT_INTERNA  112215 non-null  object
 56  SG_UF_INTE  112215 non-null  object
 57  ID_RG_INTE  112215 non-null  object
 58  CO_RG_INTE  112215 non-null  object
 59  ID_MN_INTE  112215 non-null  object
 60  CO_MU_INTE  112215 non-null  object
 61  UTI         112215 non-null  Int32
 62  SUPORT_VEN  112215 non-null  Int32
 63  AMOSTRA     112215 non-null  Int32
 64  DT_COLETA   112215 non-null  object
 65  TP_AMOSTRA  112215 non-null  Int32
 66  PCR_RESUL   112215 non-null  Int32
 67  POS_PCRFLU  112215 non-null  Int32
 68  POS_PCROUT  112215 non-null  Int32
 69  CLASSI_FIN  112215 non-null  Int32
 70  CRITERIO    112215 non-null  Int32
 71  EVOLUCAO    112215 non-null  object
 72  DT_ENCERRA  112215 non-null  object
 73  DT_DIGITA   112215 non-null  object
 74  HISTO_VGM   112215 non-null  Int32
 75  DOR_ABD     112215 non-null  Int32
 76  FADIGA      112215 non-null  Int32
 77  PERD_OLFT   112215 non-null  Int32
 78  PERD_PALA   112215 non-null  Int32
 79  TOMO_RES    112215 non-null  Int32
 80  TP_TES_AN   112215 non-null  Int32
 81  RES_AN      112215 non-null  Int32
 82  ESTRANG     112215 non-null  Int32
 83  VACINA_COV  112215 non-null  Int32
 84  FNT_IN_COV  112215 non-null  Int32
 85  TRAT_COV    112215 non-null  Int32
 86  CO_DETEC    112215 non-null  Int32
 87  REINF       112215 non-null  Int32
 88  Coriza      112215 non-null  int64
dtypes: Int32(56), int64(8), object(25)
memory usage: 59.1+ MB

In [ ]:
# Removendo agora todas os nulos
df_final.dropna(inplace=True)

In [ ]:
# A Coluna CS-ESCOL_N tem uma valor de 0 que não deixa converter para int
# Transformando esse valor de 0
df_final['CS_ESCOL_N'].unique()

array([5.0, 2.0, 9.0, 3.0, 1.0, 0.0, 4.0, '0', '3', '9', '5', '1', '2',
       '4'], dtype=object)

In [ ]:
# Transformando para float as colunas
df_final[['CS_ESCOL_N', 'TP_TES_AN']] = df_final[['CS_ESCOL_N', 'TP_TES_AN']].astype('float')

Vendo o formato dos campos, colocar essa parte mais para cima quando for finalizado o modelo

In [55]:
colunas_data = ['DT_NOTIFIC', 'DT_SIN_PRI']

colunas_int= ['PUERPERA', 'SURTO_SG', 'GARGANTA', 'DIARREIA', 'VOMITO',
'CARDIOPATI', 'HEMATOLOGI', 'SIND_DOWN', 'HEPATICA', 'ASMA',
'DIABETES', 'NEUROLOGIC', 'PNEUMOPATI', 'IMUNODEPRE', 'RENAL',
'OBESIDADE', 'OUT_MORBI', 'VACINA', 'ANTIVIRAL',
'POS_PCRFLU', 'POS_PCROUT', 'DOR_ABD', 'FADIGA','CS_ESCOL_N', 'PERD_OLFT',
'PERD_PALA', 'TRAT_COV', 'CO_DETEC', 'ESTRANG',
'RES_AN', 'TP_TES_AN', 'TOMO_RES', 'CO_REGIONA', 'CS_RACA', 'CO_MUN_RES', 'CS_ZONA', 'NOSOCOMIAL',
'AVE_SUINO', 'FEBRE', 'TOSSE', 'DISPNEIA', 'DESC_RESP', 'SATURACAO',
'FATOR_RISC', 'HOSPITAL', 'UTI', 'SUPORT_VEN', 'AMOSTRA', 'TP_AMOSTRA',
'PCR_RESUL', 'CLASSI_FIN', 'CRITERIO', 'HISTO_VGM', 'VACINA_COV',
'FNT_IN_COV', 'REINF']

# df_final[colunas_data] =  df_final[colunas_data].astype('datetime64')
for i in  colunas_int:
    print(i)
    df_final[i] =  df_final[i].astype('Int32')

df_final.head()

PUERPERA
SURTO_SG
GARGANTA
DIARREIA
VOMITO
CARDIOPATI
HEMATOLOGI
SIND_DOWN
HEPATICA
ASMA
DIABETES
NEUROLOGIC
PNEUMOPATI
IMUNODEPRE
RENAL
OBESIDADE
OUT_MORBI
VACINA
ANTIVIRAL
POS_PCRFLU
POS_PCROUT
DOR_ABD
FADIGA
CS_ESCOL_N
PERD_OLFT
PERD_PALA
TRAT_COV
CO_DETEC
ESTRANG
RES_AN
TP_TES_AN
TOMO_RES
CO_REGIONA
CS_RACA
CO_MUN_RES
CS_ZONA
NOSOCOMIAL
AVE_SUINO
FEBRE
TOSSE
DISPNEIA
DESC_RESP
SATURACAO
FATOR_RISC
HOSPITAL
UTI
SUPORT_VEN
AMOSTRA
TP_AMOSTRA
PCR_RESUL
CLASSI_FIN
CRITERIO
HISTO_VGM
VACINA_COV
FNT_IN_COV
REINF

,DT_NOTIFIC,SEM_NOT,DT_SIN_PRI,SEM_PRI,SG_UF_NOT,ID_REGIONA,CO_REGIONA,ID_MUNICIP,CO_MUN_NOT,ID_UNIDADE,CO_UNI_NOT,CS_SEXO,DT_NASC,NU_IDADE_N,TP_IDADE,COD_IDADE,CS_GESTANT,CS_RACA,CS_ESCOL_N,ID_PAIS,CO_PAIS,SG_UF,ID_RG_RESI,CO_RG_RESI,ID_MN_RESI,CO_MUN_RES,CS_ZONA,SURTO_SG,NOSOCOMIAL,AVE_SUINO,FEBRE,TOSSE,GARGANTA,DISPNEIA,DESC_RESP,SATURACAO,DIARREIA,VOMITO,PUERPERA,FATOR_RISC,CARDIOPATI,HEMATOLOGI,SIND_DOWN,HEPATICA,ASMA,DIABETES,NEUROLOGIC,PNEUMOPATI,IMUNODEPRE,RENAL,OBESIDADE,OUT_MORBI,VACINA,ANTIVIRAL,HOSPITAL,DT_INTERNA,SG_UF_INTE,ID_RG_INTE,CO_RG_INTE,ID_MN_INTE,CO_MU_INTE,UTI,SUPORT_VEN,AMOSTRA,DT_COLETA,TP_AMOSTRA,PCR_RESUL,POS_PCRFLU,POS_PCROUT,CLASSI_FIN,CRITERIO,EVOLUCAO,DT_ENCERRA,DT_DIGITA,HISTO_VGM,DOR_ABD,FADIGA,PERD_OLFT,PERD_PALA,TOMO_RES,TP_TES_AN,RES_AN,ESTRANG,VACINA_COV,FNT_IN_COV,TRAT_COV,CO_DETEC,REINF,Coriza
1,27/02/2023,9,25/02/2023,8,PR,02RS METROPOLITANA,1356,CURITIBA,410690,HOSPITAL UNIVERSITARIO EVANGELICO MACKENZIE,15245,M,03/12/2022,2,2,2002,6,4,5,BRASIL,1,PR,02RS METROPOLITANA,1356.0,CURITIBA,410690,1,9,2,2,1,1,2,1,1,1,9,9,9,2,9,9,9,9,9,9,9,9,9,9,9,9,9,2,1,25/02/2023,PR,02RS METROPOLITANA,1356.0,CURITIBA,410690.0,2,3,1,27/02/2023,1,1,2,1,2,1,1.0,13/03/2023,27/02/2023,0,9,9,9,9,9,9,4,2,2,2,2,9,2,0
3,21/03/2023,12,18/03/2023,11,PR,17RS LONDRINA,1371,LONDRINA,411370,HOSPITAL DO CORACAO UNIDADE BELA SUICA,7758391,F,27/02/1931,92,3,3092,5,1,2,BRASIL,1,PR,17RS LONDRINA,1371.0,LONDRINA,411370,1,2,2,2,2,2,1,2,2,2,2,2,9,2,9,9,9,9,9,9,9,9,9,9,9,9,2,2,1,18/03/2023,PR,17RS LONDRINA,1371.0,LONDRINA,411370.0,2,3,1,21/03/2023,1,4,9,9,5,1,1.0,27/03/2023,22/03/2023,0,2,2,2,2,3,2,1,2,1,2,2,2,2,0
11,18/04/2023,16,15/04/2023,15,MS,EX ARS DE CAMPO GRANDE,1975,CAMPO GRANDE,500270,EBSERH HOSP UNIV MARIA APARECIDA PEDROSSIAN,9709,M,13/07/1985,37,3,3037,6,4,2,BRASIL,1,MS,EX ARS DE CAMPO GRANDE,1975.0,CHAPADAO DO SUL,500295,1,2,2,2,1,1,2,1,1,1,2,2,9,2,9,9,9,9,9,9,9,9,9,9,9,9,9,9,1,18/04/2023,MS,EX ARS DE CAMPO GRANDE,1975.0,CAMPO GRANDE,500270.0,1,1,1,19/04/2023,1,1,1,2,1,1,1.0,17/07/2023,20/04/2023,0,2,2,2,2,9,9,4,2,1,2,9,2,2,0
12,25/04/2023,17,22/04/2023,16,RS,013 CRS,1609,SANTA CRUZ DO SUL,431680,HOSPITAL SANTA CRUZ,2254964,M,14/03/2023,1,2,2001,6,1,5,BRASIL,1,RS,013 CRS,1609.0,HERVEIRAS,430957,2,9,2,2,2,1,2,1,1,1,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,1,9,2,1,22/04/2023,RS,013 CRS,1609.0,SANTA CRUZ DO SUL,431680.0,1,1,1,25/04/2023,1,2,9,9,4,1,9.0,25/04/2023,28/04/2023,0,2,2,2,2,9,9,4,2,2,2,2,9,2,0
13,12/04/2023,15,07/04/2023,14,SP,GVE XXI PRESIDENTE PRUDENTE,1346,PRESIDENTE PRUDENTE,354140,HOSPITAL UNIMED,7701810,M,14/03/2023,1,2,2001,6,1,9,BRASIL,1,SP,GVE XXI PRESIDENTE PRUDENTE,1346.0,ALVARES MACHADO,350130,1,9,2,1,2,1,2,1,1,1,2,2,9,2,9,9,9,9,9,9,9,9,9,9,9,9,9,2,1,11/04/2023,SP,GVE XXI PRESIDENTE PRUDENTE,1346.0,PRESIDENTE PRUDENTE,354140.0,2,2,1,12/04/2023,1,1,2,1,2,1,1.0,25/05/2023,27/04/2023,0,2,2,2,2,9,9,4,2,2,2,2,9,2,1

In [61]:
# Plotando por tipo e vendo se faltou alguma coisa

# df_float = df_final.select_dtypes(include=[float])
# df_float.head(20)

# # Plotando os int
# df_int = df_final.select_dtypes(include=[int])
# df_int.head(20)

# Plotando Object
df_object= df_final.select_dtypes(include=[object])
df_object.head(20)


# Analisar as colunas CO_REGIONA, CO_MUN_RES, CO_MUN_NOT, CO_UNI_NOT

,DT_NOTIFIC,DT_SIN_PRI,SG_UF_NOT,ID_REGIONA,ID_MUNICIP,ID_UNIDADE,CS_SEXO,DT_NASC,COD_IDADE,ID_PAIS,CO_PAIS,SG_UF,ID_RG_RESI,CO_RG_RESI,ID_MN_RESI,DT_INTERNA,SG_UF_INTE,ID_RG_INTE,CO_RG_INTE,ID_MN_INTE,CO_MU_INTE,DT_COLETA,EVOLUCAO,DT_ENCERRA,DT_DIGITA
1,27/02/2023,25/02/2023,PR,02RS METROPOLITANA,CURITIBA,HOSPITAL UNIVERSITARIO EVANGELICO MACKENZIE,M,03/12/2022,2002,BRASIL,1,PR,02RS METROPOLITANA,1356.0,CURITIBA,25/02/2023,PR,02RS METROPOLITANA,1356.0,CURITIBA,410690.0,27/02/2023,1.0,13/03/2023,27/02/2023
3,21/03/2023,18/03/2023,PR,17RS LONDRINA,LONDRINA,HOSPITAL DO CORACAO UNIDADE BELA SUICA,F,27/02/1931,3092,BRASIL,1,PR,17RS LONDRINA,1371.0,LONDRINA,18/03/2023,PR,17RS LONDRINA,1371.0,LONDRINA,411370.0,21/03/2023,1.0,27/03/2023,22/03/2023
11,18/04/2023,15/04/2023,MS,EX ARS DE CAMPO GRANDE,CAMPO GRANDE,EBSERH HOSP UNIV MARIA APARECIDA PEDROSSIAN,M,13/07/1985,3037,BRASIL,1,MS,EX ARS DE CAMPO GRANDE,1975.0,CHAPADAO DO SUL,18/04/2023,MS,EX ARS DE CAMPO GRANDE,1975.0,CAMPO GRANDE,500270.0,19/04/2023,1.0,17/07/2023,20/04/2023
12,25/04/2023,22/04/2023,RS,013 CRS,SANTA CRUZ DO SUL,HOSPITAL SANTA CRUZ,M,14/03/2023,2001,BRASIL,1,RS,013 CRS,1609.0,HERVEIRAS,22/04/2023,RS,013 CRS,1609.0,SANTA CRUZ DO SUL,431680.0,25/04/2023,9.0,25/04/2023,28/04/2023
13,12/04/2023,07/04/2023,SP,GVE XXI PRESIDENTE PRUDENTE,PRESIDENTE PRUDENTE,HOSPITAL UNIMED,M,14/03/2023,2001,BRASIL,1,SP,GVE XXI PRESIDENTE PRUDENTE,1346.0,ALVARES MACHADO,11/04/2023,SP,GVE XXI PRESIDENTE PRUDENTE,1346.0,PRESIDENTE PRUDENTE,354140.0,12/04/2023,1.0,25/05/2023,27/04/2023
15,02/05/2023,28/04/2023,MS,EX ARS DE CAMPO GRANDE,PARAISO DAS AGUAS,PRONTO ATENDIMENTO MEDICO LAURENTINA CORREA LEITE,M,20/03/2016,3007,BRASIL,1,MS,EX ARS DE CAMPO GRANDE,1975.0,PARAISO DAS AGUAS,01/05/2023,MS,EX ARS DE CAMPO GRANDE,1975.0,CAMPO GRANDE,500270.0,02/05/2023,1.0,16/05/2023,02/05/2023
19,21/04/2023,18/04/2023,PR,17RS LONDRINA,LONDRINA,ISCAL,F,08/02/2016,3007,BRASIL,1,PR,17RS LONDRINA,1371.0,LONDRINA,21/04/2023,PR,17RS LONDRINA,1371.0,LONDRINA,411370.0,22/04/2023,1.0,19/05/2023,19/05/2023
21,10/05/2023,25/04/2023,BA,NUCLEO REGIONAL DE SAUDE LESTE,SALVADOR,HOSPITAL GERAL ROBERTO SANTOS,F,22/05/2021,3001,BRASIL,1,BA,NUCLEO REGIONAL DE SAUDE LESTE,1380.0,SALVADOR,09/05/2023,BA,NUCLEO REGIONAL DE SAUDE LESTE,1380.0,SALVADOR,292740.0,10/05/2023,1.0,18/05/2023,18/05/2023
22,31/05/2023,16/04/2023,BA,NUCLEO REGIONAL DE SAUDE LESTE,SALVADOR,HOSPITAL SAO RAFAEL,F,14/08/1936,3086,BRASIL,1,BA,NUCLEO REGIONAL DE SAUDE LESTE,1380.0,LAURO DE FREITAS,18/04/2023,BA,NUCLEO REGIONAL DE SAUDE LESTE,1380.0,SALVADOR,292740.0,18/04/2023,1.0,31/05/2023,31/05/2023
28,27/06/2023,17/06/2023,MG,CORONEL FABRICIANO,TIMOTEO,HOSPITAL E MATERNIDADE DE TIMOTEO,F,26/06/2001,3021,BRASIL,1,MG,CORONEL FABRICIANO,1468.0,TIMOTEO,22/06/2023,MG,CORONEL FABRICIANO,1468.0,TIMOTEO,316870.0,22/06/2023,1.0,28/06/2023,28/06/2023
29,03/07/2023,02/07/2023,SP,GVE XVI BOTUCATU,BOTUCATU,HOSPITAL DAS CLINICAS DA FACULDADE DE MEDICINA DE BOTUCATU,M,17/10/2022,2009,BRASIL,1,SP,GVE XVI BOTUCATU,1341.0,TORRE DE PEDRA,02/07/2023,SP,GVE XVI BOTUCATU,1341.0,BOTUCATU,350750.0,02/07/2023,1.0,07/07/2023,03/07/2023
30,24/07/2023,17/07/2023,RS,006 CRS,PASSO FUNDO,HOSPITAL SAO VICENTE DE PAULO,M,20/04/2023,2003,BRASIL,1,RS,006 CRS,1611.0,TAPEJARA,20/07/2023,RS,006 CRS,1611.0,PASSO FUNDO,431410.0,24/07/2023,1.0,16/08/2023,24/07/2023
32,25/05/2023,22/05/2023,PI,4 GRS TERESINA,TERESINA,UNIDADE DE PRONTO ATENDIMENTO DR ANTONIO DIB TAJRA,F,05/04/1930,3093,BRASIL,1,PI,4 GRS TERESINA,1883.0,TERESINA,25/05/2023,PI,4 GRS TERESINA,1883.0,TERESINA,221100.0,25/05/2023,2.0,26/05/2023,31/07/2023
35,29/07/2023,22/07/2023,RS,014 CRS,SANTA ROSA,HOSPITAL VIDA SAUDE,F,14/01/2021,3002,BRASIL,1,RS,014 CRS,1602.0,BOA VISTA DO BURICA,29/07/2023,RS,014 CRS,1602.0,SANTA ROSA,431720.0,29/07/2023,1.0,04/09/2023,14/08/2023
38,29/04/2023,29/04/2023,SC,TUBARAO,TUBARAO,HOSPITAL NOSSA SENHORA DA CONCEICAO,M,24/08/1957,3065,BRASIL,1,SC,TUBARAO,1555.0,CAPIVARI DE BAIXO,29/04/2023,SC,TUBARAO,1555.0,TUBARAO,421870.0,29/04/2023,2.0,29/04/2023,15/09/2023
41,13/10/2023,06/10/2023,PB,X NRS SOUSA,SOUSA,HOSPITAL DISTRITAL DEP MANOEL GONCALVES DE ABRANTES,M,11/08/2021,3002,BRASIL,1,PB,X NRS SOUSA,1426.0,NAZAREZINHO,10/10/2023,PB,X NRS SOUSA,1426.0,SOUSA,251620.0,10/10/2023,1.0,23/10/2023,13/10/2023
44,16/11/2023,09/11/2023,RS,006 CRS,NAO-ME-TOQUE,HOSPITAL ALTO JACUI NAO ME TOQUE,M,20/05/1929,3094,BRASIL,1,RS,006 CRS,1611.0,NAO-ME-TOQUE,16/11/2023,RS,006 CRS,1611.0,NAO-ME-TOQUE,431265.0,16/11/2023,1.0,24/11/2023,16/11/2023
46,18/11/2023,10/11/2023,GO,PIRINEUS,ANAPOLIS,UPA III DR ALAIR MAFRA ANAPOLIS GOIAS,M,24/02/1968,3055,BRASIL,1,GO,PIRINEUS,1792.0,ANAPOLIS,14/11/2023,GO,PIRINEUS,1792.0,ANAPOLIS,520110.0,18/11/2023,1.0,22/11/2023,22/11/2023
48,23/11/2023,08/09/2023,MG,BELO HORIZONTE,BETIM,HOSPITAL MATER DEI SA BETIM,F,18/06/1953,3070,BRASIL,1,MG,BELO HORIZONTE,1449.0,BETIM,09/09/2023,MG,BELO HORIZONTE,1449.0,BETIM,310670.0,09/09/2023,1.0,14/12/2023,14/12/2023
49,13/12/2023,14/10/2023,SP,GVE I CAPITAL,SAO PAULO,HOSP MUN GILSON DE CASSIA MARQUES DE CARVALHO,M,04/04/2023,2006,BRASIL,1,SP,GVE I CAPITAL,1331.0,SAO PAULO,21/10/2023,SP,GVE I CAPITAL,1331.0,SAO PAULO,355030.0,21/10/2023,1.0,13/12/2023,13/12/2023

In [ ]:
# Colunas dt

# Modeling
Iniciando a modelagem do problema e separando em treino e teste

In [36]:
from sklearn.metrics import accuracy_score, f1_score, recall_score
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [37]:
# Separando em x e em y

In [38]:
# Separando em treino e teste
x_train,x_test, y_train, y_test =  train_test_split()

ValueError: At least one array required as input